apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  labels:
    app: my-replicaset
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: my-replicaset
  template:
    metadata:
      labels:
        app: my-replicaset
    spec:
      containers:
      - name: my-replicaset
        image: nginx:latest
        ports:
        - name: web
          containerPort:  80
          protocol: TCP