volume:
  app-vol:

networks:
  app-net:

services:
  app-node:
    depends_on:
      - ps-app
      - nginx-app
    build: .
    ports:
      - 3000:3000
    networks:
      - app-net
  nginx-app:
    image: nginx:latest
    ports:
      - 80:80
    networks:
      - app-net
  ps-app:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - app-vol:/var/lib/postgresql/data
    networks:
      - app-net