apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-dev
  template:
    metadata:
      labels:
        app: myapp-dev
    spec:
      containers:
      - name: myapp-container
        image: myapp-image:latest
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service-dev
  namespace: dev
spec:
  selector:
    app: myapp-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080